export const ICON_TYPE = {
  MAP: 'MAP',
  SMILE: 'SMILE',
  FROWN: 'FROWN',
  STAR: 'STAR',
  CAMERA: 'CAMERA',
  GIFT: 'GIFT',
  PLUS: 'PLUS',
  CART: 'CART',
  FOOTBALL_BALL: 'FOOTBALL_BALL',
  ARROW_RIGHT: 'ARROW_RIGHT',
  TIMES: 'TIMES',
};
